Added golden test suite
MegaIng/etca-asm pull request #20
Opened 2022-08-11 22:37 UTC by MegaIng

Many of the tests in this base list are based on the once found in the test suite for the k-spec written by Grape.

2022-08-11 22:46 UTC, EnderShadow submitted a review, later dismissed

2022-08-12 05:23 UTC, EnderShadow approved these changes, later dismissed

2022-08-12 19:18 UTC, EnderShadow commented
No, don't explicitly use 3.10 in the shebang. There's already a runtime check for the version. Hard coding 3.10 makes it break on future versions of python

2022-08-12 19:21 UTC, MegaIng commented
@EnderShadow That is the only way to get it to work while directly executing. If you want to use a later version of python, explicitly call it with that version of python. We can also change this back to `python3` if ubuntu ever upgrades to `3.10` by default. If you don't agree with hardcoding `3.10`, I would suggest to just remove the shebang and always require a call to python.

2022-08-12 19:23 UTC, EnderShadow requested changes
We already have a version check for 3.10 in the code. Hard coding 3.10 breaks the code for future versions of python.

2022-08-12 19:23 UTC, EnderShadow commented on etc-as.py
> +#!/usr/bin/env python3.10
```suggestion
#!/usr/bin/env python3
```

2022-08-12 19:23 UTC, EnderShadow commented on tests/golden/golden_tester_generic.py
> +    parser.add_argument("-c", "--command", action="store", default="python3.10 etc-as.py",
```suggestion
    parser.add_argument("-c", "--command", action="store", default="python3 etc-as.py",
```

2022-08-12 19:23 UTC, EnderShadow commented on tests/golden/golden_tester_generic.py
> +#!/usr/bin/env python3.10
```suggestion
#!/usr/bin/env python3
```

2022-08-12 19:26 UTC, EnderShadow commented
@MegaIng By that same logic, we should leave the shebang and require explicit use of python3.10 to run it if you have multiple versions installed

2022-08-12 19:52 UTC, JKTKops commented
Personally I'd prefer leaving the shebang with 3.10 (can always change it in the future if needed). I'm working on a system (via `make`, which is good for this kind of thing despite its flaws) which should get beginners up and running as fast as possible via

1. checking for python3.10 or better
2. walking through the install if not present
3. Copying a runner script to /usr/bin
4. copying the python stuff to /usr/lib or wherever
5. runner script (`etc-as`) discovers and uses latest python version explicitly

My biggest complaint with this method is only that it requires `sudo`. It is no longer a challenge to keep a beginner up to date and we don't have to worry about the beginner experience outside of the runner script which can handle everything.

2023-03-01 19:42 UTC, EnderShadow commented
I no longer care enough about the whole 3 vs 3.10 thing

2023-03-01 19:42 UTC, EnderShadow submitted a review, later dismissed

2023-03-01 20:18 UTC, JKTKops approved these changes, later dismissed

2023-03-01 23:20 UTC, EnderShadow approved these changes

2023-03-01 23:21 UTC, merged